### ISSUE TITLE
NS Record is deleted when trying to update it.

### ISSUE THREAD

**Issue by hyberdk** [garysharp/DnsServerApi#3]
Hi Gary, 

I think I found a bug in your code, but can you please check.. The steps I make to reproduce it is:

1. create a new zone
2. then update the SOA record with the information I need.
3. then update the NS record that is automatically created by the MS DNS server.

When I update the NS record and it invokes the `var wmiResult = instance.InvokeMethod("Modify", wmiParams, null);` the record is deleted on the server. It updates the SOA record fine.

The function is this one:

```
        public static void ModifyRecordInternal(this WindowsDnsZone zone, DnsRecord record)
        {
            if (zone == null)
                throw new ArgumentNullException(nameof(zone));
            if (record == null)
                throw new ArgumentNullException(nameof(record));

            var state = zone.GetRecordStateInternal(record);

            if (state == null)
                throw new ArgumentException("Record must be created by the provider");

            using (var instance = zone.server.WmiGetInstance(state.WmiPath))
            {
                using (var wmiParams = instance.GetMethodParameters("Modify"))
                {
                    wmiParams["TTL"] = (uint)record.TimeToLive.TotalSeconds;

                    // populate record-specific parameters
                    PopulateRecordParameters(zone, record, wmiParams);

                    var wmiResult = instance.InvokeMethod("Modify", wmiParams, null);
                    var wmiPath = (string)wmiResult["RR"];
                    var newState = new WindowsDnsRecordState(wmiPath);

                    zone.SetRecordStateInternal(record, newState);
                }
            }
        }
```

on a side note, should your code automatically update the NS record (if needed) when the SOA record is updated or what is your take on that?

Let me know if you want TCPdumps of the actual traffic.

Esben

**Comment by garysharp** [comment]
Hi Esben,

I've tried to re-create the problem, but not having much success yet. The following sample code works as expected for me:

```csharp
// create zone
var zone = server.CreateZone("myzone.mock");

// update SOA record
var soa = zone.StartOfAuthority;
soa.TimeToLive = TimeSpan.FromMinutes(30);
soa.ResponsiblePerson = "responsible.hostmaster.";
soa.Save();

// update NS record
var nsRecord = zone.NameServers.First();
nsRecord.NameServer = "srvdev-sec.";
nsRecord.Save();

// add NS record
var newNsRecord = zone.CreateNSRecord(zone.DomainName, TimeSpan.FromHours(1), "srvdev-pri.");
```

We'll speak in a few hours and compare notes.

Gary

**Comment by garysharp** [comment]
As we discovered a few weeks ago, when calling the modify record API for Windows DNS (for example [A Record Modify](https://docs.microsoft.com/en-us/windows/win32/dns/microsoftdns-atype-modify)) if no properties have changed the server deletes the record - very strange.

Version 0.9.1-beta adds change tracking to records so that the Windows DNS provider can skip modifying the record unless a change was actually made. Binaries have been published to Nuget.
